version: '3.5'

services: 
  sitecore_base:
    image: sitecore_base:${TAG}
    build:
      context: .\sitecore-xp0-images\xp-base
      args:
        SITECORE_ZIP_FILE: ${SITECORE_ZIP_FILE}
        SIF_VERSION: ${SIF_VERSION}
  
  sitecore_base_webserver:
    image: sitecore_base_webserver:${TAG}
    build:
      context: .\sitecore-xp0-images\xp-base-webserver
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    depends_on:
      - "sitecore_base"
  
  sitecore_solr:
    image: sitecore_solr:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_solr
    build:
      context: .\sitecore-xp0-images\xp-solr
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    environment:
      SOLR_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_solr
      SOLR_CORE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
      SOLR_PORT: ${SOLR_PORT}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    ports:
      - ${SOLR_PORT}:${SOLR_PORT}
    volumes:
      - ${HOST_CERTIFICATE_PATH}:C:\Certificates
      - ${HOST_SOLR_DATA_PATH}:C:\SolrData
    restart: on-failure
    depends_on:
      - "sitecore_base"
  
  sitecore_sqlserver:
    image: sitecore_sqlserver:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_sqlserver
    build:
      context: .\sitecore-xp0-images\xp-sqlserver
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      SQLSERVER_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_sqlserver
      DATABASE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${HOST_SQLSERVER_DATA_PATH}:C:\SitecoreDatabases
    ports:
      - ${SQL_PORT}:1433
    restart: on-failure
    depends_on:
      - "sitecore_base"