version: '3.5'

services: 
  sitecore_base:
    image: ${SITECORE_RESOURCE_IMG}:${SITECORE_TAG}
    build:
      context: .\Sitecore\xp_base
      args:
        WEB_SERVER_IMG: ${ASPNET_RUNTIME_IMG}
        WEB_SERVER_IMG_TAG: ${ASPNET_RUNTIME_IMG_TAG}
        SITECORE_ZIP_FILE: ${SITECORE_ZIP_FILE}
        SIF_VERSION: ${SIF_VERSION}

  sitecore_solr:
    image: ${SITECORE_SOLR_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_SOLR_IMG}
    build:
      context: .\Sitecore\xp_solr
      args:
        OPENJDK_SOLR_IMG: ${OPENJDK_SOLR_IMG}
        OPENJDK_SOLR_IMG_TAG: ${OPENJDK_SOLR_IMG_TAG}
        SOURCE_IMG: ${SITECORE_RESOURCE_IMG}
        SOURCE_IMG_TAG: ${SITECORE_TAG}
        SOLR_PREFIX: ${SITECORE_INSTANCE_PREFIX}
        SOLR_HOST_NAME: ${SITECORE_SOLR_IMG}
        CERT_EXPORT_PASSWORD: ${CERT_EXPORT_PASSWORD}
        SIF_VERSION: ${SIF_VERSION}
    ports:
      - ${SOLR_PORT}:8983
    restart: on-failure
    volumes:
      - ${SITECORE_SOLR_MOUNT_HOST}:C:\data
    depends_on:
      - "sitecore_base"

  sitecore_sqlserver:
    image: ${SITECORE_SQL_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_SQL_IMG}
    build:
      context: .\Sitecore\xp_sqlserver
      args:
        SOURCE_IMG: ${SITECORE_RESOURCE_IMG}
        SOURCE_IMG_TAG: ${SITECORE_TAG}
        MSSQL_IMG: ${MSSQL_IMG}
        MSSQL_IMG_TAG: ${MSSQL_IMG_TAG}
        DBPREFIX: ${SITECORE_INSTANCE_PREFIX}
        SQLHOSTNAME: ${SITECORE_SQL_IMG}
        SQL_ADMIN_PASSWORD: ${SQL_ADMIN_PASSWORD}
    ports:
      - ${SQL_SERVER_MAP_PORT}:1433
    restart: on-failure
    volumes:
      - ${SITECORE_SQL_MOUNT_HOST}:C:\data
    depends_on:
      - "sitecore_base"

  sitecore_identityserver:
    image: ${SITECORE_IDENTITYSERVER_IMG}:${SITECORE_TAG}
    container_name: ${IDENTITYSERVER_SITE}
    build:
        context: .\Sitecore\xp_identityserver
        args:
          SOURCE_IMG: ${SITECORE_RESOURCE_IMG}
          SOURCE_IMG_TAG: ${SITECORE_TAG}
          SITECORE_IDENTITYSERVER_SITENAME: ${IDENTITYSERVER_SITE}
          SITECORE_IDENTITYSERVER_CLIENTSECRET: ${SITECORE_IDENTITYSERVER_CLIENTSECRET}
          SQL_HOST: ${SITECORE_SQL_IMG}
          SQL_ADMIN_USER: ${SQL_ADMIN_USER}
          SQL_ADMIN_PASSWORD: ${SQL_ADMIN_PASSWORD}
          SQL_DB_PREFIX: ${SITECORE_INSTANCE_PREFIX}
          SITECORE_SITE: ${SITECORE_SITE}
          SITECORE_SITE_PORT: ${SITECORE_HTTP_MAP_PORT}
          CERT_EXPORT_PASSWORD: ${CERT_EXPORT_PASSWORD}
          IDENTITYSERVER_MAP_PORT: ${IDENTITYSERVER_MAP_PORT}
    environment:
      DEFAULT_PORT: ${IDENTITYSERVER_MAP_PORT}
    ports:
        - ${IDENTITYSERVER_MAP_PORT}:${IDENTITYSERVER_MAP_PORT}
    restart: on-failure
    volumes:
      - ${SITECORE_IDENTITYSERVER_LOGS_MOUNT_HOST}:C:/inetpub/wwwroot/${IDENTITYSERVER_SITE}/logs
    depends_on:
      - "sitecore_sqlserver"
      - "sitecore_base"

  sitecore_xconnect:
    image: ${SITECORE_XCONNECT_IMG}:${SITECORE_TAG}
    container_name: ${XCONNECT_SITE}
    build:
      context: .\Sitecore\xp_xconnect
      args:
        SOURCE_IMG: ${SITECORE_RESOURCE_IMG}
        SOURCE_IMG_TAG: ${SITECORE_TAG}
        SOLR_URL: ${SOLR_URL}
        SOLR_HOST_NAME: ${SITECORE_SOLR_IMG}
        SQL_DB_PREFIX: ${SITECORE_INSTANCE_PREFIX}
        XCONNECT_SITE: ${XCONNECT_SITE}
        XCONNECT_CLIENT_CERT: ${XCONNECT_CLIENT_CERT}
        CERT_EXPORT_PASSWORD: ${CERT_EXPORT_PASSWORD}
        XCONNECT_PORT: ${XCONNECT_MAP_PORT}
        SQL_HOST: ${SITECORE_SQL_IMG}
        SQL_ADMIN_USER: ${SQL_ADMIN_USER}
        SQL_ADMIN_PASSWORD: ${SQL_ADMIN_PASSWORD}
    environment:
      XCONNECT_DEFAULT_PORT: ${XCONNECT_MAP_PORT}
    ports:
      - ${XCONNECT_MAP_PORT}:${XCONNECT_MAP_PORT}
    restart: on-failure
    volumes:
      - ${SITECORE_XCONNECT_LOG_MOUNT_HOST}:C:/inetpub/wwwroot/${XCONNECT_SITE}/App_Data/Logs
    depends_on:
      - "sitecore_solr"
      - "sitecore_sqlserver"
      - "sitecore_base"

  sitecore_xconnect_automationengine:
    image: ${SITECORE_XCONNECT_AUTOMATIONENGINE_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_XCONNECT_AUTOMATIONENGINE_IMG}
    build: 
      context: .\Sitecore\xp_xconnect_automationengine
      args:
        XCONNECT_IMG: ${SITECORE_XCONNECT_IMG}
        XCONNECT_IMG_TAG: ${SITECORE_TAG}
        WEB_SERVER_IMG: ${ASPNET_RUNTIME_IMG}
        WEB_SERVER_IMG_TAG: ${ASPNET_RUNTIME_IMG_TAG}
        XCONNECT_SITE: ${XCONNECT_SITE}
        XCONNECT_CLIENT_CERT: ${XCONNECT_CLIENT_CERT}
        XCONNECT_CERT_PASSWORD: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${SITECORE_XCONNECT_AUTOMATIONENGINE_LOG_MOUNT_HOST}:C:/AutomationEngine/App_Data/logs
    restart: on-failure
    depends_on:
      - "sitecore_xconnect"
  
  sitecore_xconnect_processingengine:
    image: ${SITECORE_XCONNECT_PROCESSINGENGINE_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_XCONNECT_PROCESSINGENGINE_IMG}
    build:
      context: .\Sitecore\xp_xconnect_processingengine
      args:
        XCONNECT_IMG: ${SITECORE_XCONNECT_IMG}
        XCONNECT_IMG_TAG: ${SITECORE_TAG}
        WEB_SERVER_IMG: ${ASPNET_RUNTIME_IMG}
        WEB_SERVER_IMG_TAG: ${ASPNET_RUNTIME_IMG_TAG}
    volumes:
      - ${SITECORE_XCONNECT_PROCESSINGENGINE_LOG_MOUNT_HOST}:C:/ProcessingEngine/App_Data/logs
    depends_on:
      - "sitecore_sqlserver"
      - "sitecore_xconnect"
  
  sitecore_xconnect_indexworker:
    image: ${SITECORE_XCONNECT_INDEXWORKER_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_XCONNECT_INDEXWORKER_IMG}
    build:
      context: .\Sitecore\xp_xconnect_indexworker
      args:
        XCONNECT_IMG: ${SITECORE_XCONNECT_IMG}
        XCONNECT_IMG_TAG: ${SITECORE_TAG}
        WEB_SERVER_IMG: ${ASPNET_RUNTIME_IMG}
        WEB_SERVER_IMG_TAG: ${ASPNET_RUNTIME_IMG_TAG}
        SOLR_HOST_NAME: ${SITECORE_SOLR_IMG}
        SOLR_URL: ${SOLR_URL}
        CERT_EXPORT_PASSWORD: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${SITECORE_XCONNECT_INDEXWORKER_LOG_MOUNT_HOST}:C:/IndexWorker/App_Data/logs
    restart: on-failure
    depends_on:
      - "sitecore_xconnect"
      - "sitecore_solr"

  sitecore_xp0:
    image: ${SITECORE_XP_INSTANCE_IMG}:${SITECORE_TAG}
    container_name: ${SITECORE_SITE}
    build:
      context: .\Sitecore\xp_sc91xp0
      args:
        SOURCE_IMG: ${SITECORE_RESOURCE_IMG}
        SOURCE_IMG_TAG: ${SITECORE_TAG}
        XCONNECT_SITE: ${XCONNECT_SITE}
        XCONNECT_PORT: ${XCONNECT_MAP_PORT}
        XCONNECT_CLIENT_CERT: ${XCONNECT_CLIENT_CERT}
        SITECORE_IDENTITYSERVER_SITENAME: ${IDENTITYSERVER_SITE}
        IDENTITYSERVER_MAP_PORT: ${IDENTITYSERVER_MAP_PORT}
        SITECORE_IDENTITYSERVER_CLIENTSECRET: ${SITECORE_IDENTITYSERVER_CLIENTSECRET}
        CERT_EXPORT_PASSWORD: ${CERT_EXPORT_PASSWORD}
        SITE_NAME: ${SITECORE_SITE}
        DEFAUL_HTTP_PORT: ${SITECORE_HTTP_MAP_PORT}
        SOLR_URL: ${SOLR_URL}
        SOLR_HOST_NAME: ${SITECORE_SOLR_IMG}
        SQL_HOSTNAME: ${SITECORE_SQL_IMG}
        SQL_ADMIN_USER: ${SQL_ADMIN_USER}
        SQL_ADMIN_PASSWORD: ${SQL_ADMIN_PASSWORD}
        SQL_DB_PREFIX: ${SITECORE_INSTANCE_PREFIX}
        SITECORE_ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
    environment:
      HTTP_PORT_DEFAULT: ${SITECORE_HTTP_MAP_PORT}
    ports:
      - ${SITECORE_HTTP_MAP_PORT}:${SITECORE_HTTP_MAP_PORT}
    restart: on-failure
    volumes:
      - ${SITECORE_SITE_MOUNT_HOST}:C:/${SITECORE_SITE}
      - ${SITECORE_PROJECT_SRC_MOUNT}:C:/UnicornSource
    depends_on:
      - "sitecore_solr"
      - "sitecore_sqlserver"
      - "sitecore_xconnect"
      - "sitecore_identityserver"