version: '3.5'

services: 
  sitecore_base:
    image: sitecore_base:${TAG}
    build:
      context: .\sitecore-xp0-images\xp-base
      args:
        SITECORE_ZIP_FILE: ${SITECORE_ZIP_FILE}
        SIF_VERSION: ${SIF_VERSION}
  
  sitecore_base_webserver:
    image: sitecore_base_webserver:${TAG}
    build:
      context: .\sitecore-xp0-images\xp-base-webserver
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    depends_on:
      - "sitecore_base"
  
  sitecore_solr:
    image: sitecore_solr:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_solr
    build:
      context: .\sitecore-xp0-images\xp-solr
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    environment:
      SOLR_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_solr
      SOLR_CORE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
      SOLR_PORT: ${SOLR_PORT}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    ports:
      - ${SOLR_PORT}:${SOLR_PORT}
    volumes:
      - ${HOST_CERTIFICATE_PATH}:C:\Certificates
      - ${HOST_SOLR_DATA_PATH}:C:\SolrData
    restart: on-failure
    depends_on:
      - "sitecore_base"
  
  sitecore_sqlserver:
    image: sitecore_sqlserver:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_sqlserver
    build:
      context: .\sitecore-xp0-images\xp-sqlserver
      args:
        XP_RESOURCE_IMG: sitecore_base
        XP_RESOURCE_IMG_TAG: ${TAG}
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      SQLSERVER_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_sqlserver
      DATABASE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${HOST_SQLSERVER_DATA_PATH}:C:\SitecoreDatabases
    ports:
      - ${SQL_PORT}:1433
    restart: on-failure
    depends_on:
      - "sitecore_base"
  
  sitecore_identityserver:
    image: sitecore_identityserver:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_identityserver.dev.local
    build:
      context: .\sitecore-xp0-images\xp-identityserver
      args:
        XP_WEBSERVER_IMG: sitecore_base_webserver
        XP_WEBSERVER_IMG_TAG: ${TAG}
    environment:
      SITECORE_IDENTITYSERVER_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_identityserver.dev.local
      SITECORE_IDENTITYSERVER_PORT: ${IDENTITYSERVER_PORT}
      SITECORE_IDENTITYSERVER_CLIENT_SECRET: ${SITECORE_IDENTITYSERVER_CLIENT_SECRET}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
      SQLSERVER_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_sqlserver
      DATABASE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
      SQL_ADMIN_SECRET: ${SA_PASSWORD}
      SITECORE_SITE_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}.dev.local
      SITECORE_SITE_PORT: ${SITECORE_SITE_PORT}
    ports:
      - ${IDENTITYSERVER_PORT}:${IDENTITYSERVER_PORT}
    volumes:
      - ${HOST_IDENTITYSERVER_WEBROOT}:C:\inetpub\wwwroot\${SITECORE_INSTANCE_PREFIX}_identityserver.dev.local
      - ${HOST_CERTIFICATE_PATH}:C:/Certificates
    restart: on-failure
    depends_on:
      - "sitecore_base_webserver"
      - "sitecore_sqlserver"

  sitecore_xconnect:
    image: sitecore_xconnect:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_xconnect.dev.local
    build:
      context: .\sitecore-xp0-images\xp-xconnect
      args:
        XP_WEBSERVER_IMG: sitecore_base_webserver
        XP_WEBSERVER_IMG_TAG: ${TAG}
    environment:
      SITECORE_XCONNECT_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_xconnect.dev.local
      SITECORE_XCONNECT_CLIENT_CERT_NAME: ${SITECORE_INSTANCE_PREFIX}_xconnect_client.dev.local
      SITECORE_XCONNECT_PORT: ${XCONNECT_PORT}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
      SITECORE_SOLR_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_solr
      SITECORE_SOLR_PORT: ${SOLR_PORT}
      SQLSERVER_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_sqlserver
      SQL_ADMIN_SECRET: ${SA_PASSWORD}
      SITECORE_INSTANCE_PREFIX: ${SITECORE_INSTANCE_PREFIX}
    ports:
      - ${XCONNECT_PORT}:${XCONNECT_PORT}
    volumes:
      - ${HOST_XCONNECT_WEBROOT}:C:\inetpub\wwwroot\${SITECORE_INSTANCE_PREFIX}_xconnect.dev.local
      - ${HOST_CERTIFICATE_PATH}:C:/Certificates
    restart: on-failure
    depends_on:
      - "sitecore_base_webserver"
      - "sitecore_sqlserver"
      - "sitecore_solr"

  sitecore_xconnect_automationengine:
    image: sitecore_xconnect_automationengine:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_xconnect_automationengine
    build:
      context: .\sitecore-xp0-images\xp-xconnect-automationengine
    environment:
      SITECORE_XCONNECT_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_xconnect.dev.local
      SITECORE_XCONNECT_PORT: ${XCONNECT_PORT}
      SITECORE_XCONNECT_CLIENT_CERT_NAME: ${SITECORE_INSTANCE_PREFIX}_xconnect_client.dev.local
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${HOST_XCONNECT_WEBROOT}:C:\xConnectJobs
      - ${HOST_XCONNECT_AUTOMATION_ENGINE}:C:/AutomationEngine
      - ${HOST_CERTIFICATE_PATH}:C:/Certificates
    restart: on-failure
    depends_on:
      - "sitecore_xconnect"

  sitecore_xconnect_indexworker:
    image: sitecore_xconnect_indexworker:${TAG}
    container_name: ${SITECORE_INSTANCE_PREFIX}_xconnect_indexworker
    build:
      context: .\sitecore-xp0-images\xp-xconnect-indexworker
    environment:
      SITECORE_SOLR_HOST_NAME: ${SITECORE_INSTANCE_PREFIX}_solr
      SITECORE_SOLR_PORT: ${SOLR_PORT}
      CERT_EXPORT_SECRET: ${CERT_EXPORT_PASSWORD}
    volumes:
      - ${HOST_XCONNECT_WEBROOT}:C:\xConnectJobs
      - ${HOST_XCONNECT_INDEX_WORKER}:C:/IndexWorker
      - ${HOST_CERTIFICATE_PATH}:C:/Certificates
    restart: on-failure
    depends_on:
      - "sitecore_xconnect"