version: '3.5'

services:
  openjdk_solr:
    image: sitecore-openjdk-solr721:sitecore91x
    build:
      context: .\openjdk_solr
      args:
        OPENJDK_ZIP_PACKAGE_NAME: java-1.8.0-openjdk-1.8.0.161-1.b14.ojdkbuild.windows.x86_64.zip
        SOLR_ZIP_PACKAGE: Solr-7.2.1.zip

  mssqlserver2017_dev:
    image: sitecore-sqlserver2017-developer:sitecore91x
    build:
      context: .\mssqlserver
      args:
        MSSQL_INSTALLATION_FILE: SQLServer2017-DEV-x64-ENU.exe
  
  aspnet_runtime_472:
    image: sitecore-webserver:sitecore91x
    build:
      context: .\aspnet472